package detect

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// opencodePluginTemplate is the schmux plugin for OpenCode.
// It handles status signaling, failure capture, and stop gating.
const opencodePluginTemplate = `// Generated by schmux — do not edit manually.
// This plugin provides lifecycle hooks for schmux session monitoring.

import { appendFileSync, readFileSync, existsSync } from "fs";

const eventsFile = process.env.SCHMUX_EVENTS_FILE;

function appendEvent(event) {
  if (!eventsFile) return;
  const line = JSON.stringify({ ts: new Date().toISOString(), ...event });
  appendFileSync(eventsFile, line + "\n");
}

function classifyError(error) {
  if (!error) return "other";
  const e = error.toLowerCase();
  if (e.includes("no such file") || e.includes("not found") || e.includes("enoent")) return "not_found";
  if (e.includes("permission denied") || e.includes("eacces")) return "permission";
  if (e.includes("syntax error") || e.includes("syntaxerror")) return "syntax";
  if (e.includes("command not found")) return "wrong_command";
  if (e.includes("build failed") || e.includes("compilation") || e.includes("undefined:")) return "build_failure";
  if (e.includes("fail") || e.includes("assertion") || e.includes("expected")) return "test_failure";
  if (e.includes("timeout") || e.includes("timed out")) return "timeout";
  return "other";
}

export default async ({ client }) => ({
  event: async ({ event }) => {
    if (!eventsFile) return;

    switch (event.type) {
      case "session.created":
        appendEvent({ type: "status", state: "working", message: "" });
        break;
      case "session.idle":
        appendEvent({ type: "status", state: "completed", message: "" });
        break;
      case "permission.asked":
        appendEvent({ type: "status", state: "needs_input", message: event.data?.message?.slice(0, 100) || "" });
        break;
      case "message.updated":
        if (event.data?.role === "user") {
          const intent = (event.data?.content || "").slice(0, 200);
          appendEvent({ type: "status", state: "working", message: intent, intent });
        }
        break;
      case "tool.execute.after":
        if (event.data?.error) {
          const error = String(event.data.error).slice(0, 500);
          const tool = event.data?.tool || "unknown";
          const input = JSON.stringify(event.data?.input || "").slice(0, 300);
          appendEvent({ type: "failure", tool, input, error, category: classifyError(error) });
        }
        break;
    }
  },
  stop: async () => {
    if (!eventsFile || !existsSync(eventsFile)) return;

    const content = readFileSync(eventsFile, "utf-8");
    const lines = content.trim().split("\n").filter(Boolean);

    // Check for status event
    const statusLines = lines.filter(l => l.includes('"type":"status"'));
    if (statusLines.length > 0) {
      const last = JSON.parse(statusLines[statusLines.length - 1]);
      const terminal = ["completed", "needs_input", "needs_testing", "error"];
      if (terminal.includes(last.state)) {
        // Check for reflection event
        if (lines.some(l => l.includes('"type":"reflection"'))) {
          return; // All good, allow stop
        }
        return {
          result: "prevent",
          message: 'Write a friction reflection before finishing. Append to $SCHMUX_EVENTS_FILE: {"ts":"...","type":"reflection","text":"When X, do Y instead"}',
        };
      }
    }

    return {
      result: "prevent",
      message: 'Write your status before finishing. Append to $SCHMUX_EVENTS_FILE: {"ts":"...","type":"status","state":"completed","message":"what you did"}',
    };
  },
});
`

// opencodeSetupHooks creates .opencode/plugins/schmux.ts in the workspace.
func opencodeSetupHooks(workspacePath string) error {
	pluginDir := filepath.Join(workspacePath, ".opencode", "plugins")
	pluginPath := filepath.Join(pluginDir, "schmux.ts")

	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("failed to create .opencode/plugins directory: %w", err)
	}
	if err := os.WriteFile(pluginPath, []byte(opencodePluginTemplate), 0644); err != nil {
		return fmt.Errorf("failed to write schmux plugin: %w", err)
	}
	if pkgLogger != nil {
		pkgLogger.Info("configured OpenCode plugin", "path", pluginPath)
	}
	return nil
}

// opencodeCleanupHooks removes the schmux plugin from .opencode/plugins/.
func opencodeCleanupHooks(workspacePath string) error {
	pluginPath := filepath.Join(workspacePath, ".opencode", "plugins", "schmux.ts")
	if err := os.Remove(pluginPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// opencodeWrapRemoteCommand prepends plugin file creation to a command.
// Used for remote sessions where we can't write files via local I/O.
func opencodeWrapRemoteCommand(command string) (string, error) {
	// Escape single quotes in the template for shell embedding
	escaped := strings.ReplaceAll(opencodePluginTemplate, "'", "'\\''")
	return fmt.Sprintf("mkdir -p .opencode/plugins && printf '%%s' '%s' > .opencode/plugins/schmux.ts && %s", escaped, command), nil
}
