package detect

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPluginFileStrategy_SupportsHooks(t *testing.T) {
	s, err := GetHookStrategy("plugin-file")
	if err != nil {
		t.Fatalf("GetHookStrategy: %v", err)
	}
	if !s.SupportsHooks() {
		t.Error("plugin-file should support hooks")
	}
}

func TestPluginFileStrategy_SetupAndCleanup(t *testing.T) {
	s, _ := GetHookStrategy("plugin-file")
	dir := t.TempDir()
	err := s.SetupHooks(HookContext{WorkspacePath: dir})
	if err != nil {
		t.Fatalf("SetupHooks: %v", err)
	}
	pluginPath := filepath.Join(dir, ".opencode", "plugins", "schmux.ts")
	if _, err := os.Stat(pluginPath); err != nil {
		t.Fatalf("plugin file not created: %v", err)
	}
	// Verify content looks like the expected TypeScript
	content, _ := os.ReadFile(pluginPath)
	if len(content) == 0 {
		t.Error("plugin file is empty")
	}
	if !strings.Contains(string(content), "Generated by schmux") {
		t.Error("plugin file should contain schmux header")
	}

	err = s.CleanupHooks(dir)
	if err != nil {
		t.Fatalf("CleanupHooks: %v", err)
	}
	if _, err := os.Stat(pluginPath); !os.IsNotExist(err) {
		t.Error("plugin file should be removed after cleanup")
	}
}

func TestPluginFileStrategy_WrapRemoteCommand(t *testing.T) {
	s, _ := GetHookStrategy("plugin-file")
	wrapped, err := s.WrapRemoteCommand("opencode run")
	if err != nil {
		t.Fatalf("WrapRemoteCommand: %v", err)
	}
	if wrapped == "opencode run" {
		t.Error("WrapRemoteCommand should prepend plugin setup commands")
	}
	// Should contain mkdir and the original command
	if !strings.Contains(wrapped, "opencode run") {
		t.Error("wrapped command should contain original command")
	}
	if !strings.Contains(wrapped, "mkdir -p .opencode/plugins") {
		t.Error("wrapped command should create plugin directory")
	}
}
