package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/sergeknystautas/schmux/internal/detect"
)

func main() {
	deps := detect.AllDependencies()
	byGroup := map[string][]detect.Dependency{}
	for _, d := range deps {
		byGroup[d.Group] = append(byGroup[d.Group], d)
	}

	var b bytes.Buffer
	b.WriteString("<!-- Code generated by cmd/gen-deps-doc; DO NOT EDIT. -->\n\n")
	b.WriteString("# Get the most out of schmux: optional dependencies\n\n")
	b.WriteString("schmux auto-detects these tools and enables features when present. ")
	b.WriteString("Install tracks cover macOS and Linux/WSL2 (WSL2 is how Windows is supported).\n\n")

	for _, g := range detect.Groups {
		ds := byGroup[g.ID]
		if len(ds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", g.DisplayName, g.Description)
		for _, d := range ds {
			fmt.Fprintf(&b, "### %s\n\n%s\n\n", d.DisplayName, d.Description)
			if len(d.Unlocks) > 0 {
				b.WriteString("Unlocks:\n")
				for _, u := range d.Unlocks {
					fmt.Fprintf(&b, "- %s\n", u)
				}
				b.WriteString("\n")
			}
			writeInstall(&b, "macOS", detect.InstallForOS(d.Install, "darwin", nil))
			writeInstall(&b, "Linux / WSL2", detect.InstallForOS(d.Install, "linux", nil))
			if d.DocsURL != "" {
				fmt.Fprintf(&b, "[Learn more](%s)\n\n", d.DocsURL)
			}
		}
	}

	out := filepath.Join("docs", "dependencies.md")
	if err := os.WriteFile(out, b.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", out, err)
		os.Exit(1)
	}
}

func writeInstall(b *bytes.Buffer, label string, methods []detect.InstallMethod) {
	if len(methods) == 0 {
		return
	}
	fmt.Fprintf(b, "**Install (%s):**\n\n", label)
	for _, m := range methods {
		switch {
		case m.Command != "":
			fmt.Fprintf(b, "- %s: `%s`\n", m.Label, m.Command)
		case m.URL != "":
			fmt.Fprintf(b, "- %s: %s\n", m.Label, m.URL)
		}
	}
	b.WriteString("\n")
}
