package dashboard

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/sergeknystautas/schmux/internal/config"
	"github.com/sergeknystautas/schmux/internal/oneshot"
)

// curationWriteLogEvent appends a JSON event to the curation JSONL log file.
func curationWriteLogEvent(logFile *os.File, raw json.RawMessage) {
	if logFile == nil {
		return
	}
	logFile.Write(raw)
	logFile.Write([]byte("\n"))
}

// curationWriteDebugFile writes a file to the per-run debug directory if runDir is non-empty.
func curationWriteDebugFile(runDir, filename, content string) {
	if runDir == "" {
		return
	}
	os.WriteFile(filepath.Join(runDir, filename), []byte(content), 0644)
}

// curationGenerateRunScript creates a shell script that reproduces the curator call.
func curationGenerateRunScript(cfg *config.Config, targetName, schemaLabel string, streaming bool) string {
	cmdInfo, err := oneshot.ResolveTargetCommand(cfg, targetName, schemaLabel, streaming)
	if err != nil {
		return fmt.Sprintf("#!/bin/sh\n# Could not resolve target command: %s\nexit 1\n", err)
	}

	var sb strings.Builder
	sb.WriteString("#!/bin/sh\n")
	sb.WriteString("# Reproduce this curator run\n")
	sb.WriteString("# Generated by schmux — edit freely\n\n")

	for k, v := range cmdInfo.Env {
		fmt.Fprintf(&sb, "export %s=%q\n", k, v)
	}
	if len(cmdInfo.Env) > 0 {
		sb.WriteString("\n")
	}

	// Build the command, piping prompt.txt via stdin
	var quotedArgs []string
	for _, a := range cmdInfo.Args {
		if strings.ContainsAny(a, " \t\n\"'\\$`") {
			quotedArgs = append(quotedArgs, fmt.Sprintf("%q", a))
		} else {
			quotedArgs = append(quotedArgs, a)
		}
	}
	fmt.Fprintf(&sb, "cat \"$(dirname \"$0\")/prompt.txt\" | \\\n  %s\n", strings.Join(quotedArgs, " \\\n  "))

	return sb.String()
}

// curationComplete marks a curation as failed and broadcasts the error.
func (s *Server) curationComplete(repoName string, err error) {
	s.logger.Error("curation error", "repo", repoName, "err", err)
	s.curationTracker.Complete(repoName, err)
	s.BroadcastCuratorEvent(CuratorEvent{
		Repo:      repoName,
		Timestamp: time.Now().UTC(),
		EventType: "curator_error",
		Raw:       json.RawMessage(fmt.Sprintf(`{"error":%q}`, err.Error())),
	})
}
