import type {
  WorkspaceResponse,
  SessionResponse,
  DiffResponse,
  GitGraphResponse,
} from '@dashboard/lib/types';
import type {
  ConfigResponse,
  FileDiff,
  GitGraphNode,
  GitGraphBranch,
} from '@dashboard/lib/types.generated';

export function createDemoSessions(): SessionResponse[] {
  return [
    {
      id: 'demo-sess-1',
      target: 'claude',
      branch: 'feature/user-auth',
      created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      running: true,
      attach_cmd: 'schmux attach demo-sess-1',
      nickname: 'auth-impl',
      persona_name: 'Backend Engineer',
      persona_icon: '⚙️',
      persona_color: '#6366f1',
      nudge_state: 'Working',
    },
    {
      id: 'demo-sess-2',
      target: 'claude',
      branch: 'feature/user-auth',
      created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      last_output_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      running: true,
      attach_cmd: 'schmux attach demo-sess-2',
      nickname: 'test-writer',
      persona_name: 'QA Engineer',
      persona_icon: '🧪',
      persona_color: '#10b981',
      nudge_state: 'Needs Input',
    },
  ];
}

export function createDemoWorkspaces(): WorkspaceResponse[] {
  const sessions = createDemoSessions();
  return [
    {
      id: 'demo-ws-1',
      repo: 'https://github.com/acme/api-server.git',
      repo_name: 'acme/api-server',
      branch: 'feature/user-auth',
      path: '/home/dev/workspaces/api-server-001',
      session_count: sessions.length,
      sessions,
      git_ahead: 3,
      git_behind: 0,
      git_lines_added: 147,
      git_lines_removed: 23,
      git_files_changed: 5,
      default_branch: 'main',
    },
    {
      id: 'demo-ws-2',
      repo: 'https://github.com/acme/webapp.git',
      repo_name: 'acme/webapp',
      branch: 'fix/rate-limiting',
      path: '/home/dev/workspaces/webapp-001',
      session_count: 1,
      sessions: [
        {
          id: 'demo-sess-3',
          target: 'codex',
          branch: 'fix/rate-limiting',
          created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
          running: false,
          attach_cmd: 'schmux attach demo-sess-3',
          nickname: 'rate-limiter',
        },
      ],
      git_ahead: 1,
      git_behind: 2,
      git_lines_added: 42,
      git_lines_removed: 15,
      git_files_changed: 3,
      default_branch: 'main',
    },
  ];
}

export function createDemoConfig(): ConfigResponse {
  return {
    workspace_path: '/home/dev/workspaces',
    source_code_management: 'git',
    repos: [
      { name: 'acme/webapp', url: 'https://github.com/acme/webapp.git' },
      { name: 'acme/api-server', url: 'https://github.com/acme/api-server.git' },
    ],
    run_targets: [
      { name: 'claude', type: 'promptable', command: 'claude --dangerously-skip-permissions' },
      { name: 'codex', type: 'promptable', command: 'codex --full-auto' },
    ],
    quick_launch: [],
    models: [],
    nudgenik: { enabled: false },
    branch_suggest: {},
    conflict_resolve: {},
    sessions: {},
    xterm: {},
    network: {},
    access_control: {},
    pr_review: {},
    commit_message: { target: '' },
    desync: {},
    io_workspace_telemetry: {},
    notifications: {},
    lore: {},
    subreddit: {},
    floor_manager: { enabled: false },
    remote_access: { enabled: false },
    needs_restart: false,
  } as unknown as ConfigResponse;
}

/** Workspace state after a spawn completes (for the spawn scenario) */
export function createPostSpawnWorkspaces(): WorkspaceResponse[] {
  const base = createDemoWorkspaces();
  // Add new session to first workspace
  base[0].sessions = [
    ...base[0].sessions,
    {
      id: 'demo-sess-new',
      target: 'claude',
      branch: 'feature/user-auth',
      created_at: new Date().toISOString(),
      running: true,
      attach_cmd: 'schmux attach demo-sess-new',
      nickname: 'new-agent',
      persona_name: 'Frontend Developer',
      persona_icon: '🎨',
      persona_color: '#f59e0b',
      nudge_state: 'Working',
    },
  ];
  base[0].session_count = base[0].sessions.length;
  return base;
}

/** Mock diff data for the feature/user-auth workspace */
export function createDemoDiff(workspaceId: string): DiffResponse {
  const workspace = createDemoWorkspaces().find((ws) => ws.id === workspaceId);

  if (workspaceId === 'demo-ws-2') {
    return createRateLimiterDiff(workspace);
  }

  return createAuthDiff(workspace, workspaceId);
}

function createAuthDiff(
  workspace: WorkspaceResponse | undefined,
  workspaceId: string
): DiffResponse {
  const files: FileDiff[] = [
    {
      old_path: 'src/auth/middleware.ts',
      new_path: 'src/auth/middleware.ts',
      status: 'modified',
      lines_added: 42,
      lines_removed: 8,
      is_binary: false,
      old_content: [
        'import { Request, Response, NextFunction } from "express";',
        '',
        'export function authMiddleware(req: Request, res: Response, next: NextFunction) {',
        '  const token = req.headers.authorization;',
        '  if (!token) {',
        '    return res.status(401).json({ error: "Unauthorized" });',
        '  }',
        '  next();',
        '}',
      ].join('\n'),
      new_content: [
        'import { Request, Response, NextFunction } from "express";',
        'import { verifyJWT, TokenPayload } from "./jwt";',
        'import { RateLimiter } from "./rate-limiter";',
        '',
        'const limiter = new RateLimiter({ windowMs: 15 * 60 * 1000, max: 100 });',
        '',
        'declare global {',
        '  namespace Express {',
        '    interface Request {',
        '      user?: TokenPayload;',
        '    }',
        '  }',
        '}',
        '',
        'export function authMiddleware(req: Request, res: Response, next: NextFunction) {',
        '  // Rate limiting',
        '  if (!limiter.tryConsume(req.ip ?? "unknown")) {',
        '    return res.status(429).json({ error: "Too many requests" });',
        '  }',
        '',
        '  const header = req.headers.authorization;',
        '  if (!header?.startsWith("Bearer ")) {',
        '    return res.status(401).json({ error: "Missing or invalid authorization header" });',
        '  }',
        '',
        '  const token = header.slice(7);',
        '  const payload = verifyJWT(token);',
        '  if (!payload) {',
        '    return res.status(401).json({ error: "Invalid or expired token" });',
        '  }',
        '',
        '  req.user = payload;',
        '  next();',
        '}',
      ].join('\n'),
    },
    {
      new_path: 'src/auth/jwt.ts',
      status: 'added',
      lines_added: 38,
      lines_removed: 0,
      is_binary: false,
      new_content: [
        'import jwt from "jsonwebtoken";',
        '',
        'export interface TokenPayload {',
        '  userId: string;',
        '  email: string;',
        '  role: "admin" | "user";',
        '  iat: number;',
        '  exp: number;',
        '}',
        '',
        'const SECRET = process.env.JWT_SECRET ?? "dev-secret";',
        '',
        'export function signJWT(payload: Omit<TokenPayload, "iat" | "exp">): string {',
        '  return jwt.sign(payload, SECRET, { expiresIn: "24h" });',
        '}',
        '',
        'export function verifyJWT(token: string): TokenPayload | null {',
        '  try {',
        '    return jwt.verify(token, SECRET) as TokenPayload;',
        '  } catch {',
        '    return null;',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      new_path: 'src/auth/rate-limiter.ts',
      status: 'added',
      lines_added: 29,
      lines_removed: 0,
      is_binary: false,
      new_content: [
        'interface RateLimiterOptions {',
        '  windowMs: number;',
        '  max: number;',
        '}',
        '',
        'export class RateLimiter {',
        '  private hits = new Map<string, number[]>();',
        '  private windowMs: number;',
        '  private max: number;',
        '',
        '  constructor(options: RateLimiterOptions) {',
        '    this.windowMs = options.windowMs;',
        '    this.max = options.max;',
        '  }',
        '',
        '  tryConsume(key: string): boolean {',
        '    const now = Date.now();',
        '    const timestamps = (this.hits.get(key) ?? []).filter(',
        '      (t) => now - t < this.windowMs',
        '    );',
        '    if (timestamps.length >= this.max) return false;',
        '    timestamps.push(now);',
        '    this.hits.set(key, timestamps);',
        '    return true;',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      old_path: 'src/routes/login.ts',
      new_path: 'src/routes/login.ts',
      status: 'modified',
      lines_added: 18,
      lines_removed: 5,
      is_binary: false,
      old_content: [
        'import { Router } from "express";',
        '',
        'const router = Router();',
        '',
        'router.post("/login", (req, res) => {',
        '  const { username, password } = req.body;',
        '  // TODO: implement auth',
        '  res.json({ token: "placeholder" });',
        '});',
        '',
        'export default router;',
      ].join('\n'),
      new_content: [
        'import { Router } from "express";',
        'import { signJWT } from "../auth/jwt";',
        'import { findUserByEmail, verifyPassword } from "../models/user";',
        '',
        'const router = Router();',
        '',
        'router.post("/login", async (req, res) => {',
        '  const { email, password } = req.body;',
        '  if (!email || !password) {',
        '    return res.status(400).json({ error: "Email and password are required" });',
        '  }',
        '',
        '  const user = await findUserByEmail(email);',
        '  if (!user || !await verifyPassword(password, user.password_hash)) {',
        '    return res.status(401).json({ error: "Invalid credentials" });',
        '  }',
        '',
        '  const token = signJWT({ userId: user.id, email: user.email, role: user.role });',
        '  res.json({ token, user: { id: user.id, email: user.email, role: user.role } });',
        '});',
        '',
        'export default router;',
      ].join('\n'),
    },
    {
      old_path: 'tests/auth.test.ts',
      new_path: 'tests/auth.test.ts',
      status: 'modified',
      lines_added: 20,
      lines_removed: 10,
      is_binary: false,
      old_content: [
        'import { describe, it, expect } from "vitest";',
        'import { authMiddleware } from "../src/auth/middleware";',
        '',
        'describe("authMiddleware", () => {',
        '  it("rejects missing token", () => {',
        '    const req = { headers: {} } as any;',
        '    const res = { status: () => ({ json: () => {} }) } as any;',
        '    authMiddleware(req, res, () => {});',
        '  });',
        '});',
      ].join('\n'),
      new_content: [
        'import { describe, it, expect, vi } from "vitest";',
        'import { authMiddleware } from "../src/auth/middleware";',
        'import { signJWT } from "../src/auth/jwt";',
        '',
        'describe("authMiddleware", () => {',
        '  it("rejects missing authorization header", () => {',
        '    const req = { headers: {}, ip: "127.0.0.1" } as any;',
        '    const res = { status: vi.fn().mockReturnThis(), json: vi.fn() } as any;',
        '    authMiddleware(req, res, vi.fn());',
        '    expect(res.status).toHaveBeenCalledWith(401);',
        '  });',
        '',
        '  it("accepts valid JWT token", () => {',
        '    const token = signJWT({ userId: "1", email: "test@example.com", role: "user" });',
        '    const req = { headers: { authorization: `Bearer ${token}` }, ip: "127.0.0.1" } as any;',
        '    const res = {} as any;',
        '    const next = vi.fn();',
        '    authMiddleware(req, res, next);',
        '    expect(next).toHaveBeenCalled();',
        '    expect(req.user.email).toBe("test@example.com");',
        '  });',
        '});',
      ].join('\n'),
    },
  ];

  return {
    workspace_id: workspaceId,
    repo: workspace?.repo ?? '',
    branch: workspace?.branch ?? '',
    files,
  };
}

function createRateLimiterDiff(workspace: WorkspaceResponse | undefined): DiffResponse {
  const files: FileDiff[] = [
    {
      old_path: 'src/middleware/rate-limiter.ts',
      new_path: 'src/middleware/rate-limiter.ts',
      status: 'modified',
      lines_added: 22,
      lines_removed: 9,
      is_binary: false,
      old_content: [
        'export class SlidingWindowLimiter {',
        '  private windows = new Map<string, number>();',
        '',
        '  constructor(private windowMs: number, private max: number) {}',
        '',
        '  isAllowed(key: string): boolean {',
        '    const now = Date.now();',
        '    const count = this.windows.get(key) ?? 0;',
        '    if (count >= this.max) return false;',
        '    this.windows.set(key, count + 1);',
        '    return true;',
        '  }',
        '}',
      ].join('\n'),
      new_content: [
        'interface WindowEntry {',
        '  count: number;',
        '  startedAt: number;',
        '}',
        '',
        'export class SlidingWindowLimiter {',
        '  private windows = new Map<string, WindowEntry>();',
        '',
        '  constructor(private windowMs: number, private max: number) {}',
        '',
        '  isAllowed(key: string): boolean {',
        '    const now = Date.now();',
        '    const entry = this.windows.get(key);',
        '',
        '    // Reset window if expired',
        '    if (entry && now - entry.startedAt >= this.windowMs) {',
        '      this.windows.delete(key);',
        '    }',
        '',
        '    const current = this.windows.get(key);',
        '    if (current && current.count >= this.max) return false;',
        '',
        '    this.windows.set(key, {',
        '      count: (current?.count ?? 0) + 1,',
        '      startedAt: current?.startedAt ?? now,',
        '    });',
        '    return true;',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      old_path: 'src/middleware/rate-limiter.test.ts',
      new_path: 'src/middleware/rate-limiter.test.ts',
      status: 'modified',
      lines_added: 14,
      lines_removed: 3,
      is_binary: false,
      old_content: [
        'import { describe, it, expect } from "vitest";',
        'import { SlidingWindowLimiter } from "./rate-limiter";',
        '',
        'describe("SlidingWindowLimiter", () => {',
        '  it("allows requests under limit", () => {',
        '    const limiter = new SlidingWindowLimiter(1000, 5);',
        '    expect(limiter.isAllowed("key")).toBe(true);',
        '  });',
        '});',
      ].join('\n'),
      new_content: [
        'import { describe, it, expect, vi } from "vitest";',
        'import { SlidingWindowLimiter } from "./rate-limiter";',
        '',
        'describe("SlidingWindowLimiter", () => {',
        '  it("allows requests under limit", () => {',
        '    const limiter = new SlidingWindowLimiter(1000, 5);',
        '    expect(limiter.isAllowed("key")).toBe(true);',
        '  });',
        '',
        '  it("blocks requests over limit", () => {',
        '    const limiter = new SlidingWindowLimiter(1000, 2);',
        '    limiter.isAllowed("key");',
        '    limiter.isAllowed("key");',
        '    expect(limiter.isAllowed("key")).toBe(false);',
        '  });',
        '',
        '  it("resets after window expires", () => {',
        '    vi.useFakeTimers();',
        '    const limiter = new SlidingWindowLimiter(1000, 1);',
        '    limiter.isAllowed("key");',
        '    expect(limiter.isAllowed("key")).toBe(false);',
        '    vi.advanceTimersByTime(1001);',
        '    expect(limiter.isAllowed("key")).toBe(true);',
        '    vi.useRealTimers();',
        '  });',
        '});',
      ].join('\n'),
    },
    {
      old_path: 'src/config/limits.ts',
      new_path: 'src/config/limits.ts',
      status: 'modified',
      lines_added: 6,
      lines_removed: 3,
      is_binary: false,
      old_content: [
        'export const RATE_LIMITS = {',
        '  api: { windowMs: 60_000, max: 100 },',
        '  auth: { windowMs: 60_000, max: 10 },',
        '};',
      ].join('\n'),
      new_content: [
        'export const RATE_LIMITS = {',
        '  api: { windowMs: 15 * 60_000, max: 200 },',
        '  auth: { windowMs: 15 * 60_000, max: 20 },',
        '  upload: { windowMs: 60 * 60_000, max: 50 },',
        '} as const;',
        '',
        'export type RateLimitKey = keyof typeof RATE_LIMITS;',
      ].join('\n'),
    },
  ];

  return {
    workspace_id: 'demo-ws-2',
    repo: workspace?.repo ?? '',
    branch: workspace?.branch ?? '',
    files,
  };
}

/** Mock git graph for the commit graph tab */
export function createDemoGitGraph(workspaceId: string): GitGraphResponse {
  const workspace = createDemoWorkspaces().find((ws) => ws.id === workspaceId);
  const branch = workspace?.branch ?? 'feature/user-auth';
  const now = Date.now();

  // Realistic-looking commit hashes (deterministic, not real)
  const HASHES: Record<string, string> = {
    '1001': 'a3f7b2c9e1d84f6a0b5c3e7d9f2a4b6c8e0d1f3a',
    '1002': 'd8e4f1a7c3b9065d2e8f4a1c7b3d9e5f0a2c6b8d',
    '1003': '7c2e9f4b1a8d36e5c0f7a2b4d6e8c1f3a5b7d9e0',
    '2001': 'f1a3b5c7d9e2f4a6b8c0d2e4f6a8b1c3d5e7f9a0',
    '2002': 'b4d6e8f0a2c4b6d8e0f2a4c6b8d0e2f4a6c8b0d2',
    '2003': 'e7f9a1c3b5d7e9f1a3c5b7d9e1f3a5c7b9d1e3f5',
    '2004': '9a1c3e5f7b9d1a3c5e7f9b1d3a5c7e9f1b3d5a7c9',
    '3001': 'c5e8a2d4f6b9c1e3a5d7f9b2c4e6a8d0f2b4c6e8',
  };
  const hash = (n: number) => HASHES[String(n)] || n.toString(16).padStart(40, 'f');

  const featureNodes: GitGraphNode[] =
    workspaceId === 'demo-ws-2'
      ? [
          {
            hash: hash(3001),
            short_hash: hash(3001).slice(0, 7),
            message: 'fix(rate-limiter): reset sliding window on expiry',
            author: 'rate-limiter',
            timestamp: new Date(now - 20 * 60 * 1000).toISOString(),
            parents: [hash(2003)],
            branches: [branch],
            is_head: [workspaceId],
            workspace_ids: [workspaceId],
          },
        ]
      : [
          {
            hash: hash(1001),
            short_hash: hash(1001).slice(0, 7),
            message: 'feat(auth): add JWT token verification and signing',
            author: 'auth-impl',
            timestamp: new Date(now - 10 * 60 * 1000).toISOString(),
            parents: [hash(1002)],
            branches: [branch],
            is_head: [workspaceId || ''],
            workspace_ids: [workspaceId || ''],
          },
          {
            hash: hash(1002),
            short_hash: hash(1002).slice(0, 7),
            message: 'feat(auth): add rate limiter middleware',
            author: 'auth-impl',
            timestamp: new Date(now - 25 * 60 * 1000).toISOString(),
            parents: [hash(1003)],
            branches: [],
            is_head: [],
            workspace_ids: [],
          },
          {
            hash: hash(1003),
            short_hash: hash(1003).slice(0, 7),
            message: 'refactor(auth): restructure auth middleware for JWT support',
            author: 'auth-impl',
            timestamp: new Date(now - 40 * 60 * 1000).toISOString(),
            parents: [hash(2003)],
            branches: [],
            is_head: [],
            workspace_ids: [],
          },
        ];

  const mainNodes: GitGraphNode[] = [
    {
      hash: hash(2001),
      short_hash: hash(2001).slice(0, 7),
      message: 'fix(api): handle empty request body gracefully',
      author: 'dev-team',
      timestamp: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
      parents: [hash(2002)],
      branches: ['main'],
      is_head: [],
      workspace_ids: [],
    },
    {
      hash: hash(2002),
      short_hash: hash(2002).slice(0, 7),
      message: 'docs: update API documentation for v2 endpoints',
      author: 'dev-team',
      timestamp: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
      parents: [hash(2003)],
      branches: [],
      is_head: [],
      workspace_ids: [],
    },
    {
      hash: hash(2003),
      short_hash: hash(2003).slice(0, 7),
      message: 'chore: bump dependencies to latest versions',
      author: 'dev-team',
      timestamp: new Date(now - 8 * 60 * 60 * 1000).toISOString(),
      parents: [hash(2004)],
      branches: [],
      is_head: [],
      workspace_ids: [],
    },
    {
      hash: hash(2004),
      short_hash: hash(2004).slice(0, 7),
      message: 'feat(db): add connection pooling configuration',
      author: 'dev-team',
      timestamp: new Date(now - 24 * 60 * 60 * 1000).toISOString(),
      parents: [],
      branches: [],
      is_head: [],
      workspace_ids: [],
    },
  ];

  const branches: Record<string, GitGraphBranch> = {
    [branch]: {
      head: workspaceId === 'demo-ws-2' ? hash(3001) : hash(1001),
      is_main: false,
      workspace_ids: [workspaceId || ''],
    },
    main: {
      head: hash(2001),
      is_main: true,
      workspace_ids: [],
    },
  };

  return {
    repo: workspace?.repo ?? '',
    nodes: [...featureNodes, ...mainNodes],
    branches,
    main_ahead_count: featureNodes.length,
    dirty_state: {
      files_changed: workspace?.git_files_changed ?? 8,
      lines_added: workspace?.git_lines_added ?? 147,
      lines_removed: workspace?.git_lines_removed ?? 23,
    },
  };
}
