// Code generated by cmd/gen-types; DO NOT EDIT.

export interface AccessControl {
  enabled: boolean;
  provider: string;
  session_ttl_minutes: number;
}

export interface AccessControlUpdate {
  enabled?: boolean;
  provider?: string;
  session_ttl_minutes?: number;
}

export interface Action {
  id: string;
  name: string;
  type: string;
  scope: string;
  template?: string;
  parameters?: ActionParameter[];
  target?: string;
  persona?: string;
  command?: string;
  learned_target?: LearnedDefault;
  learned_persona?: LearnedDefault;
  source: string;
  confidence: number;
  evidence_count?: number;
  state: string;
  use_count?: number;
  edit_count?: number;
  first_seen: string;
  last_used?: string;
  proposed_at?: string;
  pinned_at?: string;
}

export interface ActionParameter {
  name: string;
  default?: string;
}

export interface ActionRegistryResponse {
  actions: Action[];
}

export interface BranchSuggest {
  target?: string;
}

export interface BranchSuggestUpdate {
  target?: string;
}

export interface CommitMessage {
  target: string;
}

export interface CommitMessageUpdate {
  target?: string;
}

export interface ConfigResponse {
  workspace_path: string;
  source_code_management: string;
  repos: RepoWithConfig[];
  run_targets: RunTarget[];
  quick_launch: QuickLaunch[];
  external_diff_commands?: ExternalDiffCommand[];
  external_diff_cleanup_after_ms?: number;
  models: Model[];
  model_versions?: Record<string, string>;
  nudgenik: Nudgenik;
  branch_suggest: BranchSuggest;
  conflict_resolve: ConflictResolve;
  sessions: Sessions;
  xterm: Xterm;
  network: Network;
  access_control: AccessControl;
  pr_review: PrReview;
  commit_message: CommitMessage;
  desync: Desync;
  io_workspace_telemetry: IOWorkspaceTelemetry;
  notifications: Notifications;
  lore: Lore;
  subreddit: Subreddit;
  floor_manager: FloorManager;
  remote_access: RemoteAccess;
  needs_restart: boolean;
}

export interface ConfigUpdateRequest {
  workspace_path?: string;
  source_code_management?: string;
  repos?: Repo[];
  run_targets?: RunTarget[];
  quick_launch?: QuickLaunch[];
  external_diff_commands?: ExternalDiffCommand[];
  external_diff_cleanup_after_ms?: number;
  nudgenik?: NudgenikUpdate;
  branch_suggest?: BranchSuggestUpdate;
  conflict_resolve?: ConflictResolveUpdate;
  sessions?: SessionsUpdate;
  xterm?: XtermUpdate;
  network?: NetworkUpdate;
  access_control?: AccessControlUpdate;
  pr_review?: PrReviewUpdate;
  commit_message?: CommitMessageUpdate;
  desync?: DesyncUpdate;
  io_workspace_telemetry?: IOWorkspaceTelemetryUpdate;
  notifications?: NotificationsUpdate;
  lore?: LoreUpdate;
  subreddit?: SubredditUpdate;
  floor_manager?: FloorManagerUpdate;
  remote_access?: RemoteAccessUpdate;
  model_versions?: Record<string, string>;
}

export interface ConflictResolve {
  target?: string;
  timeout_ms: number;
}

export interface ConflictResolveUpdate {
  target?: string;
  timeout_ms?: number;
}

export interface CreateActionRequest {
  name: string;
  type: string;
  template?: string;
  parameters?: ActionParameter[];
  target?: string;
  persona?: string;
  command?: string;
}

export interface Desync {
  enabled: boolean;
  target: string;
}

export interface DesyncUpdate {
  enabled?: boolean;
  target?: string;
}

export interface ExternalDiffCommand {
  name: string;
  command: string;
}

export interface FileDiff {
  old_path?: string;
  new_path?: string;
  old_content?: string;
  new_content?: string;
  status?: string;
  lines_added: number;
  lines_removed: number;
  is_binary: boolean;
}

export interface FloorManager {
  enabled: boolean;
  target: string;
  rotation_threshold: number;
  debounce_ms: number;
}

export interface FloorManagerUpdate {
  enabled?: boolean;
  target?: string;
  rotation_threshold?: number;
  debounce_ms?: number;
}

export interface GitCommitDetailResponse {
  hash: string;
  short_hash: string;
  author_name: string;
  author_email: string;
  timestamp: string;
  message: string;
  parents: string[];
  is_merge: boolean;
  files: FileDiff[];
}

export interface GitGraphBranch {
  head: string;
  is_main: boolean;
  workspace_ids: string[];
}

export interface GitGraphDirtyState {
  files_changed: number;
  lines_added: number;
  lines_removed: number;
}

export interface GitGraphNode {
  hash: string;
  short_hash: string;
  message: string;
  author: string;
  timestamp: string;
  parents: string[];
  branches: string[];
  is_head: string[];
  workspace_ids: string[];
}

export interface GitGraphResponse {
  repo: string;
  nodes: GitGraphNode[];
  branches: Record<string, GitGraphBranch>;
  main_ahead_count: number;
  main_ahead_newest_timestamp?: string;
  main_ahead_next_hash?: string;
  local_truncated?: boolean;
  dirty_state?: GitGraphDirtyState;
}

export interface GitHubStatus {
  available: boolean;
  username?: string;
}

export interface IOWorkspaceTelemetry {
  enabled: boolean;
  target: string;
}

export interface IOWorkspaceTelemetryUpdate {
  enabled?: boolean;
  target?: string;
}

export interface LearnedDefault {
  value: string;
  confidence: number;
}

export interface Lore {
  enabled: boolean;
  llm_target: string;
  curate_on_dispose: string;
  auto_pr: boolean;
}

export interface LoreUpdate {
  enabled?: boolean;
  llm_target?: string;
  curate_on_dispose?: string;
  auto_pr?: boolean;
}

export interface Model {
  id: string;
  display_name: string;
  base_tool: string;
  provider: string;
  category: string;
  required_secrets?: string[];
  usage_url?: string;
  configured: boolean;
  pinned_version?: string;
  default_value: string;
}

export interface Network {
  bind_address: string;
  port: number;
  public_base_url: string;
  tls?: TLS;
}

export interface NetworkUpdate {
  bind_address?: string;
  port?: number;
  public_base_url?: string;
  tls?: TLSUpdate;
}

export interface Notifications {
  sound_disabled: boolean;
  confirm_before_close: boolean;
  suggest_dispose_after_push: boolean;
}

export interface NotificationsUpdate {
  sound_disabled?: boolean;
  confirm_before_close?: boolean;
  suggest_dispose_after_push?: boolean;
}

export interface Nudgenik {
  target?: string;
  viewed_buffer_ms: number;
  seen_interval_ms: number;
}

export interface NudgenikUpdate {
  target?: string;
  viewed_buffer_ms?: number;
  seen_interval_ms?: number;
}

export interface PRsResponse {
  prs: PullRequest[];
  last_fetched_at?: string;
  error?: string;
}

export interface Persona {
  id: string;
  name: string;
  icon: string;
  color: string;
  prompt: string;
  expectations: string;
  built_in: boolean;
}

export interface PersonaCreateRequest {
  id: string;
  name: string;
  icon: string;
  color: string;
  prompt: string;
  expectations?: string;
}

export interface PersonaListResponse {
  personas: Persona[];
}

export interface PersonaUpdateRequest {
  name?: string;
  icon?: string;
  color?: string;
  prompt?: string;
  expectations?: string;
}

export interface PrReview {
  target: string;
}

export interface PrReviewUpdate {
  target?: string;
}

export interface PromptHistoryEntry {
  text: string;
  last_seen: string;
  count: number;
}

export interface PromptHistoryResponse {
  prompts: PromptHistoryEntry[];
}

export interface PullRequest {
  number: number;
  title: string;
  body: string;
  state: string;
  repo_name: string;
  repo_url: string;
  source_branch: string;
  target_branch: string;
  author: string;
  created_at: string;
  html_url: string;
  fork_owner?: string;
  is_fork: boolean;
}

export interface QuickLaunch {
  name: string;
  command?: string;
  target?: string;
  prompt?: string;
}

export interface RemoteAccess {
  enabled: boolean;
  timeout_minutes: number;
  password_hash_set: boolean;
  notify: RemoteAccessNotify;
}

export interface RemoteAccessNotify {
  ntfy_topic: string;
  command: string;
}

export interface RemoteAccessNotifyUpdate {
  ntfy_topic?: string;
  command?: string;
}

export interface RemoteAccessUpdate {
  enabled?: boolean;
  timeout_minutes?: number;
  notify?: RemoteAccessNotifyUpdate;
}

export interface Repo {
  name: string;
  url: string;
  bare_path?: string;
}

export interface RepoConfig {
  quick_launch?: QuickLaunch[];
}

export interface RepoWithConfig {
  name: string;
  url: string;
  default_branch?: string;
  config?: RepoConfig;
}

export interface RunTarget {
  name: string;
  type: string;
  command: string;
  source?: string;
}

export interface Sessions {
  dashboard_poll_interval_ms: number;
  git_status_poll_interval_ms: number;
  git_clone_timeout_ms: number;
  git_status_timeout_ms: number;
}

export interface SessionsUpdate {
  dashboard_poll_interval_ms?: number;
  git_status_poll_interval_ms?: number;
  git_clone_timeout_ms?: number;
  git_status_timeout_ms?: number;
}

export interface Subreddit {
  target: string;
  hours: number;
}

export interface SubredditUpdate {
  target?: string;
  hours?: number;
}

export interface TLS {
  cert_path: string;
  key_path: string;
}

export interface TLSUpdate {
  cert_path?: string;
  key_path?: string;
}

export interface TLSValidateRequest {
  cert_path: string;
  key_path: string;
}

export interface TLSValidateResponse {
  valid: boolean;
  hostname?: string;
  expires?: string;
  error?: string;
}

export interface UpdateActionRequest {
  name?: string;
  template?: string;
  parameters?: ActionParameter[];
  target?: string;
  persona?: string;
  command?: string;
}

export interface Xterm {
  query_timeout_ms: number;
  operation_timeout_ms: number;
}

export interface XtermUpdate {
  query_timeout_ms?: number;
  operation_timeout_ms?: number;
}

